name: pafnucy_env
dependencies:
- conda-forge::python=3.6
- marta-sd::cudatoolkit=8.0
- marta-sd::cudnn=5.1
- marta-sd::tensorflow-gpu=1.2
- cheminfibb::tfbio-gpu=0.3
- openbabel::openbabel=2.4.1
- conda-forge::numpy>=1.12.1
- conda-forge::h5py>=2.7.0
- conda-forge::matplotlib>=2.0
- conda-forge::pandas>=0.20.2
- conda-forge::scikit-learn>=0.18.1
- conda-forge::seaborn>=0.7
- conda-forge::notebook>=5.0
- anaconda::ipywidgets>=6.0.0
